/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_ontology_remote_ontologyRemote_definitions_result$schema = z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'version': z.number().readonly(),
  'objectTypes': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'label': z.string().readonly(),
  'description': z.string().readonly(),
  'properties': z.array(z.object({
  'key': z.string().readonly(),
  'label': z.string().readonly(),
  'type': z.union([z.literal("string"), z.literal("number"), z.literal("boolean"), z.literal("date")]).readonly(),
  'required': z.boolean().readonly().optional(),
  'values': z.array(z.union([z.string(), z.number(), z.literal(false), z.literal(true)])).readonly().optional(),
})).readonly(),
})).readonly(),
  'linkTypes': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'label': z.string().readonly(),
  'from': z.intersection(z.string(), z.unknown()).readonly(),
  'to': z.intersection(z.string(), z.unknown()).readonly(),
  'cardinality': z.union([z.literal("one-to-one"), z.literal("one-to-many"), z.literal("many-to-many")]).readonly().optional(),
  'description': z.string().readonly().optional(),
})).readonly(),
  'functions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'label': z.string().readonly(),
  'description': z.string().readonly(),
  'inputs': z.array(z.object({
  'key': z.string().readonly(),
  'label': z.string().readonly(),
  'type': z.union([z.literal("string"), z.literal("number"), z.literal("boolean"), z.literal("date")]).readonly(),
  'required': z.boolean().readonly().optional(),
  'values': z.array(z.union([z.string(), z.number(), z.literal(false), z.literal(true)])).readonly().optional(),
})).readonly().optional(),
  'result': z.union([z.object({
  'kind': z.literal("scalar").readonly(),
  'type': z.union([z.literal("string"), z.literal("number"), z.literal("boolean"), z.literal("date")]).readonly(),
}), z.object({
  'kind': z.literal("object").readonly(),
  'objectType': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'kind': z.literal("object-list").readonly(),
  'objectType': z.intersection(z.string(), z.unknown()).readonly(),
})]).readonly(),
})).readonly(),
  'actions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'label': z.string().readonly(),
  'target': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'driver': z.union([z.literal("machine"), z.literal("workflow"), z.literal("agent"), z.literal("human")]).readonly(),
  'description': z.string().readonly(),
  'inputs': z.array(z.object({
  'key': z.string().readonly(),
  'label': z.string().readonly(),
  'type': z.union([z.literal("string"), z.literal("number"), z.literal("boolean"), z.literal("date")]).readonly(),
  'required': z.boolean().readonly().optional(),
  'values': z.array(z.union([z.string(), z.number(), z.literal(false), z.literal(true)])).readonly().optional(),
})).readonly().optional(),
  'result': z.intersection(z.string(), z.unknown()).readonly().optional(),
})).readonly(),
}))
const _deepseek_ai_dsh_ontology_remote_ontologyRemote_executeAction_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_ontology_remote_ontologyRemote_executeAction_parameter_1$schema = z.record(z.string(), z.union([z.string(), z.number(), z.literal(false), z.literal(true)])).readonly()
const _deepseek_ai_dsh_ontology_remote_ontologyRemote_executeAction_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'type': z.intersection(z.string(), z.unknown()).readonly(),
  'properties': z.record(z.string(), z.union([z.string(), z.number(), z.literal(false), z.literal(true)])).readonly().readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_ontology_remote_ontologyRemote_executeFunction_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_ontology_remote_ontologyRemote_executeFunction_parameter_1$schema = z.record(z.string(), z.union([z.string(), z.number(), z.literal(false), z.literal(true)])).readonly()
const _deepseek_ai_dsh_ontology_remote_ontologyRemote_executeFunction_result$schema = z.union([z.string(), z.number(), z.literal(false), z.literal(true), z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'type': z.intersection(z.string(), z.unknown()).readonly(),
  'properties': z.record(z.string(), z.union([z.string(), z.number(), z.literal(false), z.literal(true)])).readonly().readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
}), z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'type': z.intersection(z.string(), z.unknown()).readonly(),
  'properties': z.record(z.string(), z.union([z.string(), z.number(), z.literal(false), z.literal(true)])).readonly().readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
}))])
const _deepseek_ai_dsh_ontology_remote_ontologyRemote_listLinks_parameter_0$schema = z.union([z.undefined(), z.object({
  'type': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'from': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'to': z.intersection(z.string(), z.unknown()).readonly().optional(),
})])
const _deepseek_ai_dsh_ontology_remote_ontologyRemote_listLinks_result$schema = z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'type': z.intersection(z.string(), z.unknown()).readonly(),
  'from': z.intersection(z.string(), z.unknown()).readonly(),
  'to': z.intersection(z.string(), z.unknown()).readonly(),
  'createdAt': z.number().readonly(),
}))
const _deepseek_ai_dsh_ontology_remote_ontologyRemote_listObjects_parameter_0$schema = z.union([z.undefined(), z.intersection(z.string(), z.unknown())])
const _deepseek_ai_dsh_ontology_remote_ontologyRemote_listObjects_result$schema = z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'type': z.intersection(z.string(), z.unknown()).readonly(),
  'properties': z.record(z.string(), z.union([z.string(), z.number(), z.literal(false), z.literal(true)])).readonly().readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
}))

export const TYPERT = {
  package: 'aiko-dsh-bid-studio/ontology',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'aiko-dsh-bid-studio/ontology#ontologyRemote/definitions',
      service: 'ontologyRemote',
      namespace: 'ontologyRemote',
      method: 'definitions',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'aiko-dsh-bid-studio/ontology#ontologyRemote/definitions:result',
        schema: _deepseek_ai_dsh_ontology_remote_ontologyRemote_definitions_result$schema,
      },
      sourceLocation: {"file":"packages/ontology/ontology-remote/src/index.ts","line":39,"column":3},
    },
    {
      id: 'aiko-dsh-bid-studio/ontology#ontologyRemote/executeAction',
      service: 'ontologyRemote',
      namespace: 'ontologyRemote',
      method: 'executeAction',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'action',
          wire: 'action',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'aiko-dsh-bid-studio/ontology/types#OntologyActionId',
            schema: _deepseek_ai_dsh_ontology_remote_ontologyRemote_executeAction_parameter_0$schema,
          },
        },
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'aiko-dsh-bid-studio/ontology#ontologyRemote/executeAction:input',
            schema: _deepseek_ai_dsh_ontology_remote_ontologyRemote_executeAction_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'aiko-dsh-bid-studio/ontology/types#OntologyObject',
        schema: _deepseek_ai_dsh_ontology_remote_ontologyRemote_executeAction_result$schema,
      },
      sourceLocation: {"file":"packages/ontology/ontology-remote/src/index.ts","line":84,"column":9},
    },
    {
      id: 'aiko-dsh-bid-studio/ontology#ontologyRemote/executeFunction',
      service: 'ontologyRemote',
      namespace: 'ontologyRemote',
      method: 'executeFunction',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'functionId',
          wire: 'functionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'aiko-dsh-bid-studio/ontology/types#OntologyFunctionId',
            schema: _deepseek_ai_dsh_ontology_remote_ontologyRemote_executeFunction_parameter_0$schema,
          },
        },
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'aiko-dsh-bid-studio/ontology#ontologyRemote/executeFunction:input',
            schema: _deepseek_ai_dsh_ontology_remote_ontologyRemote_executeFunction_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'aiko-dsh-bid-studio/ontology/types#OntologyFunctionValue',
        schema: _deepseek_ai_dsh_ontology_remote_ontologyRemote_executeFunction_result$schema,
      },
      sourceLocation: {"file":"packages/ontology/ontology-remote/src/index.ts","line":70,"column":9},
    },
    {
      id: 'aiko-dsh-bid-studio/ontology#ontologyRemote/listLinks',
      service: 'ontologyRemote',
      namespace: 'ontologyRemote',
      method: 'listLinks',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'query',
          wire: 'query',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: 'aiko-dsh-bid-studio/ontology/types#OntologyLinkQuery',
            schema: _deepseek_ai_dsh_ontology_remote_ontologyRemote_listLinks_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'aiko-dsh-bid-studio/ontology#ontologyRemote/listLinks:result',
        schema: _deepseek_ai_dsh_ontology_remote_ontologyRemote_listLinks_result$schema,
      },
      sourceLocation: {"file":"packages/ontology/ontology-remote/src/index.ts","line":59,"column":3},
    },
    {
      id: 'aiko-dsh-bid-studio/ontology#ontologyRemote/listObjects',
      service: 'ontologyRemote',
      namespace: 'ontologyRemote',
      method: 'listObjects',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'type',
          wire: 'type',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: 'aiko-dsh-bid-studio/ontology/types#OntologyObjectTypeId',
            schema: _deepseek_ai_dsh_ontology_remote_ontologyRemote_listObjects_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'aiko-dsh-bid-studio/ontology#ontologyRemote/listObjects:result',
        schema: _deepseek_ai_dsh_ontology_remote_ontologyRemote_listObjects_result$schema,
      },
      sourceLocation: {"file":"packages/ontology/ontology-remote/src/index.ts","line":49,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Remote Consumer that keeps transport concerns out of the Provider interface.",
        "summary": "Remote Consumer that keeps transport concerns out of the Provider interface.",
        "tags": [],
        "jsDoc": "/** Remote Consumer that keeps transport concerns out of the Provider interface. */",
        "key": "ontologyRemote",
        "exportName": "OntologyRemote",
        "members": [
          {
            "kind": "method",
            "name": "definitions",
            "signature": "@Remote('definitions') definitions(): readonly OntologyDefinition[]",
            "summary": "Return every active versioned definition.",
            "jsDoc": "/**\n * Return every active versioned definition.\n * @returns Active definitions in registration order.\n */"
          },
          {
            "kind": "method",
            "name": "listObjects",
            "signature": "@Remote('listObjects') listObjects(type?: OntologyObjectTypeId): readonly OntologyObject[]",
            "summary": "Return current object snapshots.",
            "jsDoc": "/**\n * Return current object snapshots.\n * @param type - Optional object-type filter.\n * @returns Matching immutable objects.\n */"
          },
          {
            "kind": "method",
            "name": "listLinks",
            "signature": "@Remote('listLinks') listLinks(query?: OntologyLinkQuery): readonly OntologyLink[]",
            "summary": "Return current link snapshots.",
            "jsDoc": "/**\n * Return current link snapshots.\n * @param query - Optional endpoint and type filters.\n * @returns Matching immutable links.\n */"
          },
          {
            "kind": "method",
            "name": "executeFunction",
            "signature": "@Remote('executeFunction') async executeFunction( functionId: OntologyFunctionId, input: Readonly<Record<string, OntologyPropertyValue>>, ): Promise<OntologyFunctionValue>",
            "summary": "Execute one registered read-only Function.",
            "jsDoc": "/**\n * Execute one registered read-only Function.\n * @param functionId - Function id.\n * @param input - Scalar Function fields.\n * @returns Validated Function result.\n */"
          },
          {
            "kind": "method",
            "name": "executeAction",
            "signature": "@Remote('executeAction') async executeAction(action: OntologyActionId, input: Readonly<Record<string, OntologyPropertyValue>>): Promise<OntologyObject>",
            "summary": "Execute one registered Action through the Provider's declared route.",
            "jsDoc": "/**\n * Execute one registered Action through the Provider's declared route.\n * @param action - Action id.\n * @param input - Scalar Action fields.\n * @returns Object created or returned by the Action.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "OntologyActionDefinition",
            "declaration": "export interface OntologyActionDefinition {\n    readonly id: OntologyActionId;\n    readonly label: string;\n    readonly target?: OntologyObjectTypeId;\n    readonly driver: OntologyActionDriver;\n    readonly description: string;\n    readonly inputs?: readonly OntologyPropertyDefinition[];\n    readonly result?: OntologyObjectTypeId;\n}"
          },
          {
            "name": "OntologyActionDriver",
            "declaration": "export type OntologyActionDriver = 'machine' | 'workflow' | 'agent' | 'human';"
          },
          {
            "name": "OntologyActionId",
            "declaration": "export type OntologyActionId = Branded<'OntologyActionId'>;"
          },
          {
            "name": "OntologyDefinition",
            "declaration": "export interface OntologyDefinition {\n    readonly id: OntologyDefinitionId;\n    readonly version: number;\n    readonly objectTypes: readonly OntologyObjectTypeDefinition[];\n    readonly linkTypes: readonly OntologyLinkTypeDefinition[];\n    readonly functions: readonly OntologyFunctionDefinition[];\n    readonly actions: readonly OntologyActionDefinition[];\n}"
          },
          {
            "name": "OntologyDefinitionId",
            "declaration": "export type OntologyDefinitionId = Branded<'OntologyDefinitionId'>;"
          },
          {
            "name": "OntologyFunctionDefinition",
            "declaration": "export interface OntologyFunctionDefinition {\n    readonly id: OntologyFunctionId;\n    readonly label: string;\n    readonly description: string;\n    readonly inputs?: readonly OntologyPropertyDefinition[];\n    readonly result: OntologyFunctionResultDefinition;\n}"
          },
          {
            "name": "OntologyFunctionId",
            "declaration": "export type OntologyFunctionId = Branded<'OntologyFunctionId'>;"
          },
          {
            "name": "OntologyFunctionResultDefinition",
            "declaration": "export type OntologyFunctionResultDefinition = { readonly kind: 'scalar'; readonly type: OntologyScalarType; } | { readonly kind: 'object'; readonly objectType: OntologyObjectTypeId; } | { readonly kind: 'object-list'; readonly objectType: OntologyObjectTypeId; };"
          },
          {
            "name": "OntologyFunctionValue",
            "declaration": "export type OntologyFunctionValue = OntologyPropertyValue | OntologyObject | readonly OntologyObject[];"
          },
          {
            "name": "OntologyLink",
            "declaration": "export interface OntologyLink {\n    readonly id: OntologyLinkId;\n    readonly type: OntologyLinkTypeId;\n    readonly from: OntologyObjectId;\n    readonly to: OntologyObjectId;\n    readonly createdAt: number;\n}"
          },
          {
            "name": "OntologyLinkId",
            "declaration": "export type OntologyLinkId = Branded<'OntologyLinkId'>;"
          },
          {
            "name": "OntologyLinkQuery",
            "declaration": "export interface OntologyLinkQuery {\n    readonly type?: OntologyLinkTypeId;\n    readonly from?: OntologyObjectId;\n    readonly to?: OntologyObjectId;\n}"
          },
          {
            "name": "OntologyLinkTypeDefinition",
            "declaration": "export interface OntologyLinkTypeDefinition {\n    readonly id: OntologyLinkTypeId;\n    readonly label: string;\n    readonly from: OntologyObjectTypeId;\n    readonly to: OntologyObjectTypeId;\n    readonly cardinality?: 'one-to-one' | 'one-to-many' | 'many-to-many';\n    readonly description?: string;\n}"
          },
          {
            "name": "OntologyLinkTypeId",
            "declaration": "export type OntologyLinkTypeId = Branded<'OntologyLinkTypeId'>;"
          },
          {
            "name": "OntologyObject",
            "declaration": "export interface OntologyObject {\n    readonly id: OntologyObjectId;\n    readonly type: OntologyObjectTypeId;\n    readonly properties: Readonly<Record<string, OntologyPropertyValue>>;\n    readonly createdAt: number;\n    readonly updatedAt: number;\n}"
          },
          {
            "name": "OntologyObjectId",
            "declaration": "export type OntologyObjectId = Branded<'OntologyObjectId'>;"
          },
          {
            "name": "OntologyObjectTypeDefinition",
            "declaration": "export interface OntologyObjectTypeDefinition {\n    readonly id: OntologyObjectTypeId;\n    readonly label: string;\n    readonly description: string;\n    readonly properties: readonly OntologyPropertyDefinition[];\n}"
          },
          {
            "name": "OntologyObjectTypeId",
            "declaration": "export type OntologyObjectTypeId = Branded<'OntologyObjectTypeId'>;"
          },
          {
            "name": "OntologyPropertyDefinition",
            "declaration": "export interface OntologyPropertyDefinition {\n    readonly key: string;\n    readonly label: string;\n    readonly type: OntologyScalarType;\n    readonly required?: boolean;\n    readonly values?: readonly OntologyPropertyValue[];\n}"
          },
          {
            "name": "OntologyPropertyValue",
            "declaration": "export type OntologyPropertyValue = string | number | boolean;"
          },
          {
            "name": "OntologyScalarType",
            "declaration": "export type OntologyScalarType = 'string' | 'number' | 'boolean' | 'date';"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
