/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { OntologyActionId, OntologyDefinition, OntologyFunctionId, OntologyFunctionValue, OntologyLink, OntologyLinkQuery, OntologyObject, OntologyObjectTypeId, OntologyPropertyValue } from 'aiko-dsh-bid-studio/ontology/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6f6e746f6c6f677952656d6f7465 {
    definitions: () => Promise<RemoteResult<readonly OntologyDefinition[]>>
    executeAction: (action: OntologyActionId, input: Readonly<Record<string, OntologyPropertyValue>>) => Promise<RemoteResult<OntologyObject>>
    executeFunction: (functionId: OntologyFunctionId, input: Readonly<Record<string, OntologyPropertyValue>>) => Promise<RemoteResult<OntologyFunctionValue>>
    listLinks: (query?: OntologyLinkQuery) => Promise<RemoteResult<readonly OntologyLink[]>>
    listObjects: (type?: OntologyObjectTypeId) => Promise<RemoteResult<readonly OntologyObject[]>>
  }
  interface TypertRemoteMap {
    'ontologyRemote/definitions': () => Promise<RemoteResult<readonly OntologyDefinition[]>>
    'ontologyRemote/executeAction': (action: OntologyActionId, input: Readonly<Record<string, OntologyPropertyValue>>) => Promise<RemoteResult<OntologyObject>>
    'ontologyRemote/executeFunction': (functionId: OntologyFunctionId, input: Readonly<Record<string, OntologyPropertyValue>>) => Promise<RemoteResult<OntologyFunctionValue>>
    'ontologyRemote/listLinks': (query?: OntologyLinkQuery) => Promise<RemoteResult<readonly OntologyLink[]>>
    'ontologyRemote/listObjects': (type?: OntologyObjectTypeId) => Promise<RemoteResult<readonly OntologyObject[]>>
  }
  interface TypertRemoteNamespaceMap {
    'ontologyRemote': TypertRemoteNamespace$6f6e746f6c6f677952656d6f7465
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
